server:
  port: 8080
  max-http-header-size: 8KB
  server-header: "Hi" # hide tomcat version in http responses
  shutdown: graceful  # graceful shutdown
  compression:
    enabled: true
    min-response-size: 1024 # 1KB
  tomcat:
    threads.max: 200
    min-spare: 10
    connection-timeout: 300000 # 300s

spring:
  application:
    name: "main-server"
  profiles:
    active: dev
  lifecycle:
    timeout-per-shutdown-phase: 1m # graceful timeout
